const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const root = path.resolve(__dirname, "..");

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), "utf8");
}

test("Shell renders chat/terminal mode controls on the same remote session surface", () => {
  const shell = read("src/ui/Shell.jsx");
  assert.match(shell, /id="modeChatButton"/);
  assert.match(shell, /id="modeTerminalButton"/);
  assert.match(shell, /id="sessionSwitcher"/);
  assert.match(shell, /id="sessionCountPill"/);
  assert.match(shell, /id="sessionSwipeHint"/);
  assert.match(shell, /id="sessionSwipePrev"/);
  assert.match(shell, /id="sessionSwipeLabel"/);
  assert.match(shell, /id="sessionSwipeNext"/);
  assert.match(shell, /右で前/);
  assert.match(shell, /左で次/);
  assert.match(shell, /id="sessionCreatePage"/);
  assert.match(shell, /id="sessionBrowserList"/);
  assert.match(shell, /session-selected-section/);
  assert.match(shell, /session-recent-section/);
  assert.match(shell, /session-browser-section/);
  assert.match(shell, /session-create-footer/);
  assert.match(shell, /このフォルダで開始/);
  assert.match(shell, /id="sessionHiddenToggle"/);
  assert.match(shell, /隠しフォルダ/);
  assert.match(shell, /id="sessionDirectorySearch"/);
  assert.match(shell, /フォルダ名で絞り込み/);
  assert.match(shell, /id="sessionRecentClear"/);
  assert.match(shell, /履歴を消す/);
  assert.match(shell, /className="session-cwd-card" id="sessionSelectedCwd" role="status"/);
  assert.ok(shell.indexOf("session-selected-section") < shell.indexOf("session-browser-section"));
  assert.ok(shell.indexOf("id=\"sessionBrowserUp\"") < shell.indexOf("session-browser-section"));
  assert.ok(shell.indexOf("id=\"sessionDirectorySearch\"") < shell.indexOf("session-browser-section"));
  assert.match(shell, /id="sessionSwitcherOverlay"/);
  assert.match(shell, /id="openSessionList"/);
  assert.match(shell, /className="mobile-toggle side-menu-button"/);
  assert.match(shell, /className="titlebar-main"/);
  assert.match(shell, /className="pathbar"/);
  assert.match(shell, /className="pathbar-label">pwd/);
  assert.match(shell, /id="pathbarColorPicker"/);
  assert.match(shell, /className="pathbar-color-chip"/);
  assert.match(shell, /id="headerCwd"/);
  assert.match(shell, /className="title-identity"/);
  assert.match(shell, /className="titlebar-mode-icon"/);
  assert.match(shell, /screen-pill screen-pill-chat/);
  assert.match(shell, /screen-pill screen-pill-terminal/);
  assert.match(shell, /id="terminalHost"/);
  assert.match(shell, /id="terminalInputArea"/);
  assert.match(shell, /id="terminalPrompt"/);
  assert.match(shell, /id="terminalSend"/);
  assert.match(shell, /id="terminalNativeKeys"/);
  assert.match(shell, /id="terminalReconnect"/);
  assert.match(shell, /id="terminalThemeToggle"/);
  assert.match(shell, /id="terminalZoomIn"/);
  assert.match(shell, /data-terminal-ctrl-c/);
  assert.doesNotMatch(shell, /iframe/);
});

test("browser logic attaches terminal mode to the selected Codex thread through native xterm", () => {
  const main = read("public/main.js");
  assert.match(main, /function ensureNativeTerminalConnected\(options = \{\}\)/);
  assert.match(main, /new window\.CodexNativeTerminal/);
  assert.match(main, /ensureNativeTerminalConnected\(\{ focus: activeMainMode === "terminal" \}\)/);
  assert.match(main, /focus: options\.focus \?\? activeMainMode === "terminal"/);
  assert.match(main, /url\.searchParams\.set\("thread", threadId\)/);
  assert.match(main, /terminalReconnect\?\.addEventListener\("click"/);
  assert.match(main, /function submitTerminalPrompt\(\)/);
  assert.match(main, /promptInput\.addEventListener\("keydown", \(event\) => \{[\s\S]*event\.metaKey \|\| event\.ctrlKey[\s\S]*composer\.requestSubmit\(\);/);
  assert.match(main, /function applyRemoteSessionState\(state\)/);
  assert.match(main, /onSessionState: applyRemoteSessionState/);
  assert.match(main, /function setTerminalInputMode\(mode\)/);
  assert.match(main, /function showTerminalCtrlCConfirm\(\)/);
  assert.match(main, /async function copyTextToClipboard\(text\)/);
  assert.match(main, /document\.execCommand\?\.\("copy"\)/);
  assert.match(main, /const copied = await copyTextToClipboard\(text\)/);
  assert.match(main, /function showTerminalCopyFallback\(text\)/);
  assert.match(main, /terminal-copy-textarea/);
  assert.match(main, /const sessionSwipeHint = document\.querySelector\("#sessionSwipeHint"\)/);
  assert.match(main, /const sessionSwipePrev = document\.querySelector\("#sessionSwipePrev"\)/);
  assert.match(main, /const sessionSwipeLabel = document\.querySelector\("#sessionSwipeLabel"\)/);
  assert.match(main, /const sessionSwipeNext = document\.querySelector\("#sessionSwipeNext"\)/);
  assert.match(main, /const openSessionsStorageKey = "codexRemoteOpenSessions"/);
  assert.match(main, /const activeSessionStorageKey = "codexRemoteLastActiveSessionKey"/);
  assert.match(main, /const closedThreadIdsStorageKey = "codexRemoteClosedThreadIds"/);
  assert.match(main, /function rememberClosedThread\(threadId\)/);
  assert.match(main, /function forgetClosedThread\(threadId\)/);
  assert.match(main, /function addOrUpdateOpenSession\(input\)/);
  assert.match(main, /forgetClosedThread\(session\.threadId\)/);
  assert.match(main, /apiGet\("\/api\/threads"\)/);
  assert.match(main, /apiGet\("\/api\/live-threads"\)/);
  assert.match(main, /function mergeThreadRows\(historyRows = \[\], liveRows = \[\]\)/);
  assert.match(main, /project-heading-live/);
  assert.match(main, /project-live-badge/);
  assert.match(main, /thread-live-dot/);
  assert.match(main, /一覧にないthreadの履歴表示を停止しました/);
  assert.match(main, /function syncOpenSessionsFromThreads\(threads = threadCache\)/);
  assert.match(main, /closedThreadIds\.has\(thread\.id\)/);
  assert.match(main, /liveIds\.has\(session\.threadId\)/);
  assert.match(main, /rememberClosedThread\(removed\?\.threadId\)/);
  assert.match(main, /function switchOpenSessionByOffset\(offset\)/);
  assert.match(main, /function bindSessionSwipe\(\)/);
  assert.match(main, /const label = total > 1 \? `\$\{current\}\/\$\{total\} 稼働中` : total === 1 \? "1件のみ" : "稼働なし"/);
  assert.match(main, /sessionSwipePrev\?\.classList\.toggle\("active", hasPrev\)/);
  assert.match(main, /sessionSwipeNext\?\.classList\.toggle\("active", hasNext\)/);
  assert.match(main, /"右へスワイプで前へ。"/);
  assert.match(main, /"左へスワイプで次へ。"/);
  assert.match(main, /const sessionHiddenToggle = document\.querySelector\("#sessionHiddenToggle"\)/);
  assert.match(main, /const sessionDirectorySearch = document\.querySelector\("#sessionDirectorySearch"\)/);
  assert.match(main, /const sessionRecentClear = document\.querySelector\("#sessionRecentClear"\)/);
  assert.match(main, /let sessionShowHidden = false/);
  assert.match(main, /let sessionBrowserEntries = \[\]/);
  assert.match(main, /function defaultDeveloperPath\(\)/);
  assert.match(main, /return "";/);
  assert.match(main, /function openSessionCreatePage\(initialCwd = defaultDeveloperPath\(\)\)/);
  assert.match(main, /function loadSessionBrowser\(pathValue = "", options = \{\}\)/);
  assert.match(main, /function sessionDirectorySearchText\(\)/);
  assert.match(main, /function renderSessionBrowserEntries\(\)/);
  assert.match(main, /sessionBrowserEntries\.filter/);
  assert.match(main, /一致するフォルダはありません。/);
  assert.match(main, /sessionDirectorySearch\?\.addEventListener\("input", renderSessionBrowserEntries\)/);
  assert.match(main, /function clearSessionRecentHistory\(\)/);
  assert.match(main, /localStorage\.removeItem\(cwdHistoryStorageKey\)/);
  assert.match(main, /sessionRecentClear\?\.addEventListener\("click", clearSessionRecentHistory\)/);
  assert.match(main, /sessionCreateCwd = listing\.path \|\| ""/);
  assert.match(main, /sessionBrowserPath\.textContent = displayPath\(listing\.path\) \|\| "\/"/);
  assert.match(main, /renderSessionCreatePage\(\);\s+sessionBrowserEntries = listing\.entries \|\| \[\];\s+renderSessionBrowserEntries\(\);/);
  assert.match(main, /sessionSelectedCwd\.innerHTML = sessionCreateCwd[\s\S]*<span class="session-card-main">[\s\S]*<span>\$\{escapeHtml\(displayPath\(sessionCreateCwd\)\)\}<\/span>/);
  assert.doesNotMatch(main, /sessionSelectedCwd\.innerHTML = sessionCreateCwd[\s\S]*session-card-icon[\s\S]*renderSessionRecentList/);
  assert.match(main, /row\.addEventListener\("click", \(\) => loadSessionBrowser\(entry\.path\)\)/);
  assert.doesNotMatch(main, /このフォルダを選択/);
  assert.doesNotMatch(main, /session-use-current/);
  assert.match(main, /query\.set\("hidden", "1"\)/);
  assert.match(main, /sessionHiddenToggle\?\.addEventListener\("change"/);
  assert.match(main, /preserveSearch: true/);
  assert.match(main, /function startSelectedSession\(\)/);
  assert.match(main, /restoreActiveSessionFromStorage\(\);\s+connect\(\);/);
  assert.match(main, /const headerCwd = document\.querySelector\("#headerCwd"\)/);
  assert.match(main, /function displayPath\(value\)/);
  assert.match(main, /return text === home \? "~" : `~\$\{text\.slice\(home\.length\)\}`/);
  assert.match(main, /const pathbarColorPicker = document\.querySelector\("#pathbarColorPicker"\)/);
  assert.match(main, /const pathbarColorStorageKey = "codexPathbarColorsByCwd"/);
  assert.match(main, /function pathbarColorKeyFor\(cwd = currentWorkdir\)/);
  assert.match(main, /function textColorForBackground\(hexColor\)/);
  assert.match(main, /document\.documentElement\.style\.setProperty\("--user-bubble-color", nextColor\)/);
  assert.match(main, /document\.documentElement\.style\.setProperty\("--user-bubble-text", textColorForBackground\(nextColor\)\)/);
  assert.match(main, /function savePathbarColorForCurrentWorkdir\(color\)/);
  assert.match(main, /renderOpenSessionList\(\);/);
  assert.match(main, /pathbarColorPicker\?\.addEventListener\("input"/);
  assert.match(main, /function switchToOpenSession\(sessionKey\)[\s\S]*currentWorkdir = session\.cwd \|\| currentWorkdir;\s+applyPathbarColor\(\);/);
  assert.match(main, /function restoreActiveSessionFromStorage\(\)[\s\S]*currentWorkdir = saved\.cwd \|\| currentWorkdir;\s+applyPathbarColor\(\);/);
  assert.match(main, /card\.className = "session-card open-session-card"/);
  assert.match(main, /const sessionColor = pathbarColorFor\(session\.cwd\)/);
  assert.match(main, /card\.style\.setProperty\("--session-color", sessionColor\)/);
  assert.match(main, /<span class="session-column-label">Directory<\/span>/);
  assert.match(main, /<span class="session-directory-name">\$\{escapeHtml\(basenameForPath\(session\.cwd\)\)\}<\/span>/);
  assert.match(main, /<span class="session-directory-fullpath">\$\{escapeHtml\(displayPath\(session\.cwd\) \|\| "cwd未設定"\)\}<\/span>/);
  assert.match(main, /<span class="session-column-label">Session<\/span>/);
  assert.match(main, /function syncHeaderCwd\(\)/);
  assert.match(main, /headerCwd\.textContent = currentWorkdir \? displayPath\(currentWorkdir\) : cwd/);
  assert.match(main, /headerCwd\.title = currentWorkdir \|\| ""/);
  assert.match(main, /terminalSessionMeta\.textContent = `\$\{thread\}  •  \$\{cwd\}\$\{stateLabel\}`/);
  assert.match(main, /meta\.textContent = `\$\{msg\.model\}  •  \$\{msg\.clients\}端末`/);
  assert.match(main, /localStorage\.setItem\("codexMainMode", nextMode\)/);
  assert.match(main, /let terminalLongPressActive = false/);
  assert.match(main, /onLongPressActiveChange: \(active\) => \{\s+terminalLongPressActive = Boolean\(active\);/);
  assert.match(main, /document\.body\.classList\.toggle\("terminal-touch-lock", terminalLongPressActive\)/);
  assert.match(main, /function bindSessionSwipe\(\) \{\s+const surface = document\.querySelector\("\.mode-stage"\)/);
  assert.match(main, /const isSwipeBlocked = \(event\) => terminalLongPressActive \|\| isOverlayOpen\(\) \|\| isControlTarget\(event\?\.target\)/);
  assert.match(main, /const touchActivatePx = 18/);
  assert.match(main, /const touchDistanceRatio = 0\.16/);
  assert.match(main, /const touchVelocityPxPerMs = 0\.32/);
  assert.match(main, /const wheelMinThresholdPx = 42/);
  assert.match(main, /const wheelThresholdRatio = 0\.12/);
  assert.match(main, /wheelGesture\.accumX \+= event\.deltaX/);
  assert.match(main, /switched: false/);
  assert.match(main, /if \(wheelGesture\.switched\) return;/);
  assert.match(main, /const switched = switchOpenSessionByOffset\(wheelGesture\.accumX > 0 \? 1 : -1\)/);
  assert.match(main, /wheelGesture = \{ accumX: 0, lastWheelAt: now, lastSwitchAt: switched \? now : wheelGesture\.lastSwitchAt, switched \};/);
  assert.doesNotMatch(main, /const surface = document\.querySelector\("\.conversation"\)/);
  assert.doesNotMatch(main, /defaultSmartCliUrl/);
  assert.doesNotMatch(main, /terminalFrame/);
});

test("phone bridge exposes a PTY terminal websocket instead of smart-cli iframe configuration", () => {
  const server = read("scripts/start-phone.js");
  assert.match(server, /require\("node-pty"\)/);
  assert.match(server, /retainedSessionConfig = retentionConfigFromEnv\(process\.env\)/);
  assert.match(server, /createIdleRetentionTimer/);
  assert.match(server, /scheduleIdleCleanup/);
  assert.match(server, /pruneIdleRetainedSessions\(bridges/);
  assert.match(server, /pruneIdleRetainedSessions\(terminalSessions/);
  assert.match(server, /class TerminalPtySession/);
  assert.match(server, /\/api\/codex-hook/);
  assert.match(server, /normalizeHookState/);
  assert.match(server, /sessionState/);
  assert.match(server, /pruneSessionStates/);
  assert.match(server, /pty\.spawn\(executable, args/);
  assert.match(server, /enqueueOutput\(data\)/);
  assert.match(server, /flushOutput\(\)/);
  assert.match(server, /function isTerminalInterruptInput\(data\)/);
  assert.match(server, /text === "\\u001b" \|\| text\.includes\("\\u0003"\)/);
  assert.match(server, /url\.pathname !== "\/bridge" && url\.pathname !== "\/terminal"/);
  assert.match(server, /bindTerminalSocket/);
  assert.match(server, /process\.once\("SIGINT", shutdown\)/);
  assert.match(server, /process\.once\("SIGTERM", shutdown\)/);
  assert.doesNotMatch(server, /SMART_CLI_URL/);
  assert.doesNotMatch(server, /SMART_CLI_PORT/);
  assert.doesNotMatch(server, /smartCliUrl/);
  assert.doesNotMatch(server, /smartCliPort/);
});

test("terminal client bundles xterm and forwards raw terminal input", () => {
  const client = read("src/ui/terminal-client.js");
  assert.match(client, /from "@xterm\/xterm"/);
  assert.match(client, /from "@xterm\/addon-fit"/);
  assert.match(client, /connect\(\{ threadId, cwd, force = false, focus = true \} = \{\}\)/);
  assert.match(client, /if \(focus\) this\.term\.focus\(\)/);
  assert.match(client, /this\.term\.onData\(\(data\) => this\.sendInput\(data\)\)/);
  assert.match(client, /this\.ws\.send\(JSON\.stringify\(\{ type: "input", data \}\)\)/);
  assert.match(client, /msg\.type === "sessionState"/);
  assert.match(client, /this\.sessionState\?\.status === "running"/);
  assert.match(client, /function isTerminalInterruptInput\(data\)/);
  assert.match(client, /text === escapeKey \|\| text\.includes\(ctrlC\)/);
  assert.match(client, /consumeLongPressTouchEvent\(event\)/);
  assert.match(client, /event\?\.stopImmediatePropagation\?\.\(\)/);
  assert.match(client, /bindDocumentLongPressTouchGuard\(\)/);
  assert.match(client, /document\.addEventListener\("touchmove", this\.boundDocumentLongPressTouchMove, this\.longPressDocumentOptions\)/);
  assert.match(client, /onDocumentLongPressTouchMove\(event\)/);
  assert.match(client, /this\.ws\.send\(JSON\.stringify\(\{ type: "resize"/);
  assert.match(client, /terminal-joystick-overlay/);
  assert.match(client, /repeatIntervalMs = 500/);
  assert.match(client, /longPressMs = 300/);
});

test("terminal mode is hidden until selected and uses native terminal viewport", () => {
  const css = read("public/style.css");
  assert.match(css, /\.mode-stage \{/);
  assert.match(css, /body\.terminal-touch-lock,[\s\S]+touch-action: none;/);
  assert.match(css, /grid-template-rows: 96px minmax\(0, 1fr\);/);
  assert.match(css, /\.titlebar-main \{/);
  assert.match(css, /\.session-create-page,/);
  assert.match(css, /\.session-create-body \{/);
  assert.match(css, /\.session-section-heading \{/);
  assert.match(css, /\.session-browser-section \{[\s\S]*grid-column: 1 \/ -1;[\s\S]*grid-row: 2;/);
  assert.match(css, /\.session-selected-section \{[\s\S]*position: sticky;[\s\S]*grid-column: 1 \/ -1;[\s\S]*grid-row: 1;/);
  assert.match(css, /\.session-selected-section \{[\s\S]*grid-template-columns: auto minmax\(0, 1fr\) minmax\(220px, 0\.48fr\);/);
  assert.match(css, /\.session-hidden-toggle \{/);
  assert.match(css, /\.session-directory-search \{/);
  assert.match(css, /\.session-history-clear \{/);
  assert.match(css, /\.session-card-icon \{/);
  assert.match(css, /\.session-selected-section \.session-cwd-card \{[\s\S]*grid-column: 2;[\s\S]*grid-row: 2;[\s\S]*grid-template-columns: minmax\(0, 1fr\) auto;/);
  assert.match(css, /\.session-selected-section \.session-browser-toolbar \{[\s\S]*grid-column: 1;[\s\S]*grid-row: 2;[\s\S]*grid-template-columns: auto;/);
  assert.match(css, /\.session-selected-section \.session-browser-toolbar span \{\s*display: none;/);
  assert.match(css, /\.session-selected-section \.session-directory-search \{[\s\S]*grid-column: 3;[\s\S]*grid-row: 2;/);
  assert.match(css, /\.session-selected-section \.session-cwd-card \.session-card-main > span \{[\s\S]*overflow: visible;[\s\S]*text-overflow: clip;[\s\S]*white-space: normal;[\s\S]*overflow-wrap: anywhere;/);
  assert.match(css, /\.session-create-footer \{/);
  assert.match(css, /\.session-switcher-overlay \{/);
  assert.match(css, /\.session-card-row \{/);
  assert.match(css, /\.open-session-card \{[\s\S]*grid-template-columns: 10px minmax\(0, 1fr\);[\s\S]*grid-template-rows: auto auto;/);
  assert.match(css, /\.session-color-chip \{[\s\S]*background: var\(--session-color\);/);
  assert.match(css, /\.session-card-column \{/);
  assert.match(css, /\.open-session-card \.session-card-directory,[\s\S]*\.open-session-card \.session-card-name \{[\s\S]*grid-column: 2;/);
  assert.match(css, /\.open-session-card \.session-card-directory \{[\s\S]*border-bottom:/);
  assert.match(css, /\.open-session-card \.session-directory-name \{[\s\S]*font-size: 16px;[\s\S]*font-weight: 850;/);
  assert.match(css, /\.open-session-card \.session-directory-fullpath \{[\s\S]*font-size: 11px;[\s\S]*overflow-wrap: anywhere;/);
  assert.match(css, /\.open-session-card \.session-card-name \.session-card-title,[\s\S]*\.open-session-card \.session-card-name \.session-card-meta \{[\s\S]*overflow-x: auto;[\s\S]*text-overflow: clip;[\s\S]*white-space: nowrap;/);
  assert.match(css, /\.session-column-label \{[\s\S]*var\(--session-color\)/);
  assert.match(css, /\.session-card-row\.active \.open-session-card \{[\s\S]*var\(--session-color\)/);
  assert.match(css, /\.session-start-button \{/);
  assert.match(css, /\.title-identity \{/);
  assert.match(css, /\.title-status \{/);
  assert.match(css, /\.session-swipe-hint \{/);
  assert.match(css, /\.session-swipe-arrow\.active \{/);
  assert.match(css, /\.side-menu-button \{/);
  assert.match(css, /\.pathbar \{/);
  assert.match(css, /--pathbar-color: #4f8cff;/);
  assert.match(css, /--user-bubble-color: #4f8cff;/);
  assert.match(css, /--user-bubble-text: #ffffff;/);
  assert.match(css, /\.pathbar-color-picker \{/);
  assert.match(css, /\.pathbar-color-chip \{/);
  assert.match(css, /\.entry\.user \.entry-body \{[\s\S]*color: var\(--user-bubble-text\);[\s\S]*var\(--user-bubble-color\);/);
  assert.match(css, /\.entry\.user \.entry-body::before \{[\s\S]*var\(--user-bubble-text\)/);
  assert.match(css, /\.pathbar \{[\s\S]*background:[\s\S]*var\(--pathbar-color\) 38%/);
  assert.match(css, /\.pathbar \{[\s\S]*box-shadow:/);
  assert.match(css, /\.header-cwd \{[\s\S]*overflow-x: auto;[\s\S]*text-overflow: clip;[\s\S]*font-size: 15px;/);
  assert.match(css, /body\[data-main-mode="terminal"\] \.titlebar \{/);
  assert.match(css, /@media \(max-width: 520px\) \{[\s\S]*\.titlebar-mode-icon,[\s\S]*\.title-status \{[\s\S]*display: none;/);
  assert.match(css, /@media \(max-width: 520px\) \{[\s\S]*\.session-swipe-hint \{/);
  assert.match(css, /\.terminal-mode \{[\s\S]*display: none;/);
  assert.match(css, /body\[data-main-mode="terminal"\] \.conversation \{\s*display: none;/);
  assert.match(css, /body\[data-main-mode="terminal"\] \.terminal-mode \{\s*display: flex;/);
  assert.match(css, /\.terminal-native-host \{/);
  assert.match(css, /\.terminal-input-area \{/);
  assert.match(css, /\.terminal-input-mode-toggle \{/);
  assert.match(css, /\.terminal-keys-panel \{/);
  assert.match(css, /\.terminal-confirm \{/);
  assert.match(css, /\.terminal-copy-fallback \{/);
  assert.match(css, /\.terminal-copy-textarea \{/);
  assert.match(css, /\.terminal-joystick-overlay \{/);
  assert.match(css, /\.terminal-joystick-zone\.active \{/);
  assert.match(css, /\.terminal-native-keys \{/);
  assert.doesNotMatch(css, /#terminalFrame/);
});

test("build output includes the xterm bundle assets", () => {
  const html = read("public/index.html");
  assert.match(html, /terminal-client\.css/);
  assert.match(html, /terminal-client\.js/);
  const terminalClient = read("public/terminal-client.js");
  assert.match(terminalClient, /CodexNativeTerminal/);
  assert.match(terminalClient, /onLongPressActiveChange/);
  assert.match(terminalClient, /setLongPressActive/);
  assert.match(read("public/terminal-client.css"), /\.xterm/);
});

test("project hooks publish Codex lifecycle state to the remote-control bridge", () => {
  const hooks = read(".codex/hooks.json");
  const hookScript = read("scripts/codex-remote-control-state-hook.js");
  assert.match(hooks, /"UserPromptSubmit"/);
  assert.match(hooks, /"PermissionRequest"/);
  assert.match(hooks, /"Stop"/);
  assert.match(hooks, /scripts\/codex-remote-control-state-hook\.js/);
  assert.match(hookScript, /CODEX_REMOTE_HOOK_URL/);
  assert.match(hookScript, /x-codex-remote-hook-token/);
  assert.match(hookScript, /hook_event_name === "Stop"/);
});

test("browser recovers from stale no-rollout thread ids", () => {
  const main = read("public/main.js");
  assert.match(main, /function isMissingThreadError\(message\)/);
  assert.match(main, /no rollout found for thread id/);
  assert.match(main, /function recoverMissingSelectedThread\(message\)/);
  assert.match(main, /localStorage\.removeItem\("codexPhoneLastThread"\)/);
  assert.match(main, /selectedThread = ""/);
  assert.match(main, /connect\(\);/);
  assert.match(main, /if \(recoverMissingSelectedThread\(message\)\) return;/);
  assert.match(main, /if \(recoverMissingSelectedThread\(msg\.text\)\) return;/);
});
